# Generated by Django 4.1.7 on 2023-03-07 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0005_address_alter_book_author_author_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=3)),
            ],
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.AddField(
            model_name='book',
            name='countries_published_in',
            field=models.ManyToManyField(to='book_store.country'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='book_store.country'),
        ),
    ]
