# Generated by Django 4.1.7 on 2023-03-07 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0006_country_alter_address_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(max_length=100),
        ),
    ]
