# Generated by Django 4.1.7 on 2023-03-07 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0010_country_book_countries_published_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='countries_published_in',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
