# Generated by Django 4.1.7 on 2023-03-07 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0011_remove_book_countries_published_in_delete_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='countries_published_in',
            field=models.ManyToManyField(to='book_store.country'),
        ),
    ]
