# Generated by Django 4.1.7 on 2023-03-09 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0013_challenge_alter_country_options_alter_author_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Challenge',
        ),
    ]
